# Generated by Django 3.2.16 on 2023-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(editable=False, max_length=170, verbose_name='Город')),
                ('day', models.DateField(editable=False, verbose_name='Дата измерения')),
                ('pressure', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Атмосферное давление')),
                ('humidity', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Влажность')),
                ('wind', models.CharField(choices=[('N', 'NORTH'), ('W', 'WEST'), ('S', 'SOUTH'), ('E', 'EAST'), ('NE', 'NORTH_EAST'), ('NW', 'NORTH_WEST'), ('SE', 'SOUTH_EAST'), ('SW', 'SOUTH_WEST')], default='N', max_length=2, verbose_name='Направление ветра')),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Скорость ветра')),
            ],
            options={
                'verbose_name': 'Погодное измерение',
                'verbose_name_plural': 'Погодные измерения',
            },
        ),
        migrations.AddConstraint(
            model_name='weatherrecord',
            constraint=models.UniqueConstraint(fields=('day', 'city'), name='unique_day_city'),
        ),
    ]
