# Generated by Django 3.2.16 on 2023-02-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_clothitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название одежды'),
        ),
    ]
