# Generated by Django 3.2.16 on 2023-02-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_clothitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecord',
            name='city',
            field=models.CharField(max_length=170, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='day',
            field=models.DateField(verbose_name='Дата измерения'),
        ),
    ]
