# Generated by Django 3.2.16 on 2023-02-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230226_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothitem',
            old_name='thermal_resistence',
            new_name='thermal_resistance',
        ),
    ]
