# Generated by Django 3.2.14 on 2023-03-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_thermal_resistence_clothitem_thermal_resistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='temperature',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4, verbose_name='Средняя температура'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='day',
            field=models.DateTimeField(verbose_name='Дата измерения'),
        ),
    ]
