# Generated by Django 3.2.14 on 2023-03-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230301_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherrecord',
            name='wind',
        ),
    ]
