# Generated by Django 3.2.16 on 2023-03-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_weatherrecord_wind'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='general_recomendation',
            field=models.FloatField(choices=[(0.3, 'Трусы, футболка, шорты, легкие носки, сандалии'), (0.5, 'Кальсоны, рубашка с короткими рукавами, легкие брюки, легкие носки, обувь'), (0.7, 'Трусы, женское белье, чулки, платье, обувь'), (1.0, 'Трусы, рубашка, брюки, пиджак, носки, обувь'), (1.1, 'Трусы, чулки, блузка, длинная юбка, пиджак, обувь'), (1.3, 'Нижняя одежда с длинными рукавами и штанинами, рубашка, брюки, свитер, пиджак, носки, обувь'), (1.5, 'Нижняя одежда с короткими рукавами и штанинами, рубашка, брюки, жилет, пиджак, пальто, носки, обувь')], default=0.3, verbose_name='Общая рекомендация выбора одежды'),
            preserve_default=False,
        ),
    ]
