# Generated by Django 3.2.14 on 2023-03-01 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_remove_weatherrecord_wind'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='auth.user'),
            preserve_default=False,
        ),
    ]
