# Generated by Django 3.2.14 on 2023-03-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_clothitem_user'),
        ('app', '0011_alter_weatherrecord_general_recomendation'),
    ]

    operations = [
    ]
