# Generated by Django 3.2.14 on 2023-03-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20230302_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothitem',
            name='thermal_resistance',
        ),
        migrations.AddField(
            model_name='clothitem',
            name='thermal_resistance_max',
            field=models.FloatField(default=1.0, verbose_name='Тепловая устойчивость (max)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothitem',
            name='thermal_resistance_min',
            field=models.FloatField(default=1.0, verbose_name='Тепловая устойчивость (min)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='general_recomendation',
            field=models.FloatField(choices=[(0.3, 'Трусы, футболка, шорты, легкие носки, сандалии'), (0.6, 'Мужская одежда: рубашка с короткими рукавами, легкие брюки, легкие носки, обувь.Женская одежда: Трусы, женское белье, чулки, платье, обувь'), (1.0, 'Мужская одежда: Трусы, рубашка, брюки, пиджак, носки, обувьюЖенская одежда: Трусы, чулки, блузка, длинная юбка, пиджак, обувь'), (1.3, 'Нижняя одежда с длинными рукавами и штанинами, рубашка, брюки, свитер, пиджак, носки, обувь'), (1.5, 'Нижняя одежда с короткими рукавами и штанинами, рубашка, брюки, жилет, пиджак, пальто, носки, обувь'), (2.0, 'Нижняя одежда с короткими рукавами и штанинами, рубашка, брюки, пиджак,  стеганая куртка и штаны, носки, обувь, шапка, перчатки'), (2.55, 'Нижняя одежда с длинными рукавами и штанинами, термозащитная куртка и брюки, парка (аляска) с тяжелой подбивкой, штаны с тяжелой подбивкой, носки, обувь, шапка, перчатки')], default=0.3, verbose_name='Общая рекомендация выбора одежды'),
        ),
    ]
